### ISSUE TITLE
Information please ?

### ISSUE THREAD

**Issue by spordiab** [MiniJoko/NightStander#12]
Hello, first of all I wanted to thank you for your work.

My child has type 1 diabetes and it would be really great to have this device.

However, my nightscout site is not on herokuapp.com but on render.com

Can you update your code to work with any nightscout site, that would be really great.

I know it's possible but I don't know how to do it because I'm not a programmer.

If you need my render.com address to do some testing I can give it to you.

Thank you so much

**Comment by codebymini** [comment]
Heroku is now removed from the base adress. you will need to input the full adress
